### PR TITLE
Cs log team pets

### PR DESCRIPTION
**Pull request by crate1011**
fully updated pet function in main.js, serve in browser to check if it's operational!

### CODE REVIEW

**Comment by WilsonTBell** [comment]
🔫

**Comment by WilsonTBell** [comment]
👍

**Comment by WilsonTBell** [comment]
🌲

**Comment by WilsonTBell** [comment]
🐢

**Comment by WilsonTBell** [comment]
You Up?

**Comment by SAS7178** [comment]
hi

**Comment by SAS7178** [comment]
⚡

**Comment by Robert-427** [comment]
so slow

**Comment by Robert-427** [comment]
merge already

**Comment by SAS7178** [comment]
🐟

**Pull request merged**
